name: Deploy latest Vue changes to GitHub Pages

on: 
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

jobs:
  buildV:
    name: Build Shell
    runs-on: ubuntu-latest
    env:
      VITE_BUCKET: https://radek2s.github.io/Framework-Hero
      VITE_BASE_URL: Framework-Hero
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
        working-directory: ./root
      - name: Build
        run: npm run build
        working-directory: ./root
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          token: ${{ github.token }}
          branch: gh-pages 
          folder: root/dist
          target-folder: ./docs/root